In [ ]:
# from config import PreferenceSamplerConfig
# from data import PreferenceSampler, PreferenceSamplerConfig
import json
import pickle
from data import PreferenceSampler, PreferenceSamplerConfig
import os
import torch
import numpy as np

from tqdm import tqdm

from transformers import LlamaForCausalLM, AutoTokenizer, pipeline, GenerationConfig, AutoModelForCausalLM, set_seed
from collections import defaultdict
from dataclasses import dataclass, field
import gc

# from uncertainty import UncertaintyConfig, get_uncertainity_scores

/home/vbharg4@AD/.conda/envs/vllm_test/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


INFO 11-23 02:36:25 [__init__.py:216] Automatically detected platform cuda.


In [ ]:
MODEL_DIR = os.path.join('/home/vbharg4@AD', 'models')
ds_id = os.path.join(os.getcwd(), "ultrafeedback_iter1")
ref_model_path = os.path.join(MODEL_DIR, 'LLaMA3-SFT')
reward_model_path = os.path.join(MODEL_DIR, 'FsfairX-LLaMA3-RM-v0.1')

config = PreferenceSamplerConfig(dataset_dir=ds_id, ref_model_path=ref_model_path, rm_path=reward_model_path)
pref_sampler = PreferenceSampler(config=config)

20k prompts take about 2hr 30 mins and give us 80k responses.

In [ ]:
fp_1 = os.path.join(os.getcwd(), 'output_policy_1.pkl')
fp_2 = os.path.join(os.getcwd(), 'output_policy_2.pkl')

skip_sampling = os.path.exists(fp_1) and os.path.exists(fp_2)

if skip_sampling:
    pass
else:
    outputs_policy_1, outputs_policy_2 = pref_sampler.generate_responses()

    with open(os.path.join(os.getcwd(), 'output_policy_1.pkl'), mode='wb') as f:
        pickle.dump(outputs_policy_1, f)

    with open(os.path.join(os.getcwd(), 'output_policy_2.pkl'), mode='wb') as f:
        pickle.dump(outputs_policy_2, f)

INFO 11-19 17:28:56 [utils.py:233] non-default args: {'gpu_memory_utilization': 0.75, 'disable_log_stats': True, 'enforce_eager': True, 'model': '/home/vbharg4@AD/models/LLaMA3-SFT'}
INFO 11-19 17:28:56 [model.py:547] Resolved architecture: LlamaForCausalLM


`torch_dtype` is deprecated! Use `dtype` instead!


INFO 11-19 17:28:57 [model.py:1510] Using max model len 8192


2025-11-19 17:28:58,105	INFO util.py:154 -- Missing packages: ['ipywidgets']. Run `pip install -U ipywidgets`, then restart the notebook server for rich notebook output.


INFO 11-19 17:28:58 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 11-19 17:28:58 [__init__.py:381] Cudagraph is disabled under eager mode
(EngineCore_DP0 pid=3063542) INFO 11-19 17:28:58 [core.py:644] Waiting for init message from front-end.
(EngineCore_DP0 pid=3063542) INFO 11-19 17:28:58 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='/home/vbharg4@AD/models/LLaMA3-SFT', speculative_config=None, tokenizer='/home/vbharg4@AD/models/LLaMA3-SFT', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=

Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:02,  1.23it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.22it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:02<00:00,  1.23it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.63it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:02<00:00,  1.45it/s]
(EngineCore_DP0 pid=3063542) 


(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:12 [default_loader.py:267] Loading weights took 2.80 seconds
(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:12 [gpu_model_runner.py:2653] Model loading took 14.9596 GiB and 5.329133 seconds
(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:16 [gpu_worker.py:298] Available KV cache memory: 43.21 GiB
(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:16 [kv_cache_utils.py:1087] GPU KV cache size: 353,936 tokens
(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:16 [kv_cache_utils.py:1091] Maximum concurrency for 8,192 tokens per request: 43.21x
(EngineCore_DP0 pid=3063542) WARNING 11-19 17:29:17 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:17 [core.py:210] init engine (profile, create kv cache, warmup model) took 4.67 seconds
(EngineCore_DP0 pid=3063542) INFO 11-19 17:29:17 [__init__.py:381] Cudagraph is disabled under eager mode
INFO 11-19 17:29:18 [ll

Processed prompts: 100%|██████████| 80000/80000 [1:16:05<00:00, 17.52it/s, est. speed input: 2924.38 toks/s, output: 4061.69 toks/s] 


In [ ]:
fp_3 = os.path.join(os.getcwd(), 'preference_samples.json')

if not os.path.exists(fp_3):
    samples = pref_sampler.rejection_sampling(outputs_policy_1, outputs_policy_2)

    with open(os.path.join(os.getcwd(), 'preference_samples.json'), mode='w') as f:
        json.dump(samples, f, indent=4)

Loading checkpoint shards: 100%|██████████| 4/4 [00:00<00:00, 86.84it/s]
Device set to use cuda:0
Ranking prompt 20000 samples: 100%|██████████| 20000/20000 [2:08:50<00:00,  2.59it/s]  


In [6]:
first_key = list(samples.keys())[0]
samples[first_key]

{'best_response': '<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.\n2. However, it does not provide any information about the man\'s location or the surroundings.\n3. The statement "Is standing in the grass among a group of pigs on their backs near the coast" describes a specific location and situation.\n4. There is no information in the first statement that connects the man wearing a grass skirt to the location or situation described in the second statement.\n5. Therefore, we cannot conclude that "Is standing in the grass among a group of pigs on their backs near the coast" based on the information provided in the first

In [ ]:
first_key = list(samples.keys())[0]
samples[first_key]

{'best_response': '<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.\n2. However, it does not provide any information about the man\'s location or the surroundings.\n3. The statement "Is standing in the grass among a group of pigs on their backs near the coast" describes a specific location and situation.\n4. There is no information in the first statement that connects the man wearing a grass skirt to the location or situation described in the second statement.\n5. Therefore, we cannot conclude that "Is standing in the grass among a group of pigs on their backs near the coast" based on the information provided in the first

In [3]:
with open(os.path.join(os.getcwd(), '20k_responses', 'output_policy_1.pkl'), mode='rb') as f:
    outputs_policy_1 = pickle.load(f)

with open(os.path.join(os.getcwd(), '20k_responses', 'output_policy_2.pkl'), mode='rb') as f:
    outputs_policy_2 = pickle.load(f)

In [4]:
samples = defaultdict(list)
eot_id = '<|eot_id|>'

check_assertion = True

for output_policy_1, output_policy_2 in zip(outputs_policy_1, outputs_policy_2):
    prompt = output_policy_1.prompt
    if check_assertion:
        assert prompt == output_policy_2.prompt
        check_assertion = False

    for out1, out2 in zip(output_policy_1.outputs, output_policy_2.outputs):
        samples[prompt].append(prompt + out1.text + eot_id)
        samples[prompt].append(prompt + out2.text + eot_id)

In [5]:
samples['<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n'][0]

'<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n1. The initial statement describes a man wearing a grass skirt.\n2. This gives us a descriptive image of the man\'s attire, but it doesn\'t provide enough information to make conclusions about his surroundings or surroundings with animals.\n3. The absence of details about the animals or location doesn\'t allow us to deduce the situation involving pigs standing near the coast.\n4. Therefore, we can\'t conclusively say if he is standing in the grass among a group of pigs near the coast or not.\n\nConclusion: \n- not possible to tell<|eot_id|>'

In [6]:
samples = pref_sampler.rejection_sampling(outputs_policy_1, outputs_policy_2)

with open(os.path.join(os.getcwd(),'20k_responses', 'preference_samples.json'), mode='w') as f:
    json.dump(samples, f, indent=4)

Loading checkpoint shards: 100%|██████████| 4/4 [00:00<00:00, 73.99it/s]
Device set to use cuda:0
Ranking prompt 20000 samples: 100%|██████████| 20000/20000 [2:09:21<00:00,  2.58it/s]  


In [6]:
with open(os.path.join(os.getcwd(), '20k_responses', 'preference_samples.json')) as f:
        preference_pairs = json.load(f)

In [7]:
prompt, pairs = list(preference_pairs.items())[0]
best_response, worst_response = pairs['best_response'], pairs['worst_response']
print(prompt)
print(best_response)
print(worst_response)

<|start_header_id|>user<|end_header_id|>
Can we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?
Options:
- yes
- no
- it is not possible to tell A step-by-step solution is:
<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>

<|start_header_id|>user<|end_header_id|>
Can we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?
Options:
- yes
- no
- it is not possible to tell A step-by-step solution is:
<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>
1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.
2. However, it does not provide any information about the man's location or the surroundings.
3. The statement "Is standing in the grass among a group of pigs on their backs near the coast" describes a specific location and situation.
4. There is no information in the first

In [14]:
pref_sampler.dataset[0]['context_messages'][0]['content'] == prompt.removeprefix('<|start_header_id|>user<|end_header_id|>\n').removesuffix('<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n')

True

Don't need to convert back responses and prompts to the role, content format

In [20]:
from trl.data_utils import maybe_apply_chat_template
tokenizer = AutoTokenizer.from_pretrained(pref_sampler.ref_model_path)

In [23]:
maybe_apply_chat_template({
    'prompt': [{'role': 'user', 'content': prompt}],
    'chosen': [{'role': 'assistant', 'content': best_response}],
    'rejected': [{'role': 'assistant', 'content': worst_response}]
}, tokenizer=tokenizer)

{'prompt': '<|start_header_id|>user<|end_header_id|>\n<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n',
 'chosen': '<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.\n2. However, it does not provide any information about the man\'s location or the surroundings.\n3. The statement "Is standing in t

In [24]:
maybe_apply_chat_template({
    'prompt': [{'role': 'user', 'content': prompt.removeprefix('<|start_header_id|>user<|end_header_id|>\n').removesuffix('<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n')}],
    'chosen': [{'role': 'assistant', 'content': best_response.removeprefix(prompt).removesuffix('<|eot_id|>')}],
    'rejected': [{'role': 'assistant', 'content': worst_response.removeprefix(prompt).removesuffix('<|eot_id|>')}]
}, tokenizer=tokenizer)

{'prompt': '<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n',
 'chosen': '1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.\n2. However, it does not provide any information about the man\'s location or the surroundings.\n3. The statement "Is standing in the grass among a group of pigs on their backs near the coast" describes a specific location and situation.\n4. There is no information in the first statement that connects the man wearing a grass skirt to the location or situation described in the second statement.\n5. Therefore, we cannot conclude that "Is standing in the grass among a group of pigs on their backs near the coast" based on the information provided in t

Just remove the prompt prefix from the chosen and rejected responses.

In [25]:
maybe_apply_chat_template({
    'prompt': [prompt],
    'chosen': [best_response.removeprefix(prompt)],
    'rejected': [worst_response.removeprefix(prompt)]
}, tokenizer=tokenizer)

{'prompt': ['<|start_header_id|>user<|end_header_id|>\nCan we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?\nOptions:\n- yes\n- no\n- it is not possible to tell A step-by-step solution is:\n<|eot_id|>\n<|start_header_id|>assistant<|end_header_id|>\n'],
 'chosen': ['1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.\n2. However, it does not provide any information about the man\'s location or the surroundings.\n3. The statement "Is standing in the grass among a group of pigs on their backs near the coast" describes a specific location and situation.\n4. There is no information in the first statement that connects the man wearing a grass skirt to the location or situation described in the second statement.\n5. Therefore, we cannot conclude that "Is standing in the grass among a group of pigs on their backs near the coast" based on the information provided i

In [10]:
def get_uncertainity_scores_efficient_v2(preference_pairs: dict[str: dict[str: str]], first_k: int = 100) -> np.ndarray:
    """
    TODO: Improve the throughput for higher batches of responses. Right now it is just a pair of responses.
    """
    model = LlamaForCausalLM.from_pretrained(ref_model_path, device_map='cuda:0', dtype=torch.bfloat16)
    model.requires_grad_(False)
    
    if model.generation_config.temperature is None:
        model.generation_config.temperature = 1.0

    # already set
    model.generation_config.do_sample = True

    tokenizer = AutoTokenizer.from_pretrained(ref_model_path)

    model.set_attn_implementation('eager')

    samples_attn_scores = []

    if first_k <= 0:
        first_k = len(preference_pairs)

    pbar_prefernces = tqdm(list(preference_pairs.items())[:first_k])

    for idx, (prompt, pairs) in enumerate(pbar_prefernces, start=1):
        pbar_prefernces.set_description(f'Prompt {idx} uncertainty')
        best_response, worst_response = pairs['best_response'], pairs['worst_response']

        inputs = tokenizer([best_response, worst_response], return_tensors='pt', truncation=True, max_length=2048, padding=True)

        kwargs = {
            "input_ids": inputs['input_ids'].to(model.device),
            "attention_mask": inputs['attention_mask'].to(model.device),
            "use_cache": False,
            "past_key_values": None,
            "output_attentions": True,
            "output_hidden_states": False,
            "return_dict": True,
        }

        with torch.no_grad():
            output = model(**kwargs)

        attns = output.attentions

        # No squeezing
        attn_ = torch.stack([x.to(torch.float32).detach().cpu() for x in attns])

        prompt_len = len(tokenizer(prompt)['input_ids'])
        mask_sum = inputs['attention_mask'].sum(dim=-1)

        is_single_sequence = not mask_sum.shape

        if is_single_sequence:
            # mask sum is a scalar.
            span_idx = [[prompt_len, mask_sum]]
        else:
            span_idx = [[prompt_len, total_len] for total_len in mask_sum]

        sample_attn_scores = []

        for sample_idx in range(len(span_idx)):
            # layers_attn_scores = []
            # attn_ -> layers x samples x heads x seq. len x seq. len
            start, end = span_idx[sample_idx]
            # sample_KER -> layers x heads x span x span
            sample_KER = attn_[:, sample_idx, 1:, start: end, start: end]
            # log det mean over tokens (after taking diagonal, it's the last dim) and then sum over heads (2nd dim from the left side).
            layers_attn_scores = torch.diagonal(sample_KER, dim1=-2, dim2=-1).log().mean(dim=-1).sum(dim=1)
            sample_attn_scores.append(layers_attn_scores)

        samples_attn_scores.append(sample_attn_scores)

        torch.cuda.empty_cache()

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()

    return np.array(samples_attn_scores)

In [9]:
def get_uncertainity_scores_efficient(preference_pairs: dict[str: dict[str: str]], first_k: int = 100) -> np.ndarray:
    """
    TODO: Improve the throughput for higher batches of responses. Right now it is just a pair of responses.
    """
    model = LlamaForCausalLM.from_pretrained(ref_model_path, device_map='cuda:0', dtype=torch.bfloat16)
    model.requires_grad_(False)
    
    if model.generation_config.temperature is None:
        model.generation_config.temperature = 1.0

    # already set
    model.generation_config.do_sample = True

    tokenizer = AutoTokenizer.from_pretrained(ref_model_path)

    model.set_attn_implementation('eager')

    samples_attn_scores = []

    if first_k <= 0:
        first_k = len(preference_pairs)

    pbar_prefernces = tqdm(list(preference_pairs.items())[:first_k])

    for idx, (prompt, pairs) in enumerate(pbar_prefernces, start=1):
        pbar_prefernces.set_description(f'Prompt {idx} uncertainty')
        best_response, worst_response = pairs['best_response'], pairs['worst_response']

        inputs = tokenizer([best_response, worst_response], return_tensors='pt', truncation=True, max_length=2048, padding=True)

        kwargs = {
            "input_ids": inputs['input_ids'].to(model.device),
            "attention_mask": inputs['attention_mask'].to(model.device),
            "use_cache": False,
            "past_key_values": None,
            "output_attentions": True,
            "output_hidden_states": False,
            "return_dict": True,
        }

        with torch.no_grad():
            output = model(**kwargs)

        attns = output.attentions

        # No squeezing
        attn_ = torch.stack([x.to(torch.float32).detach().cpu() for x in attns])

        prompt_len = len(tokenizer(prompt)['input_ids'])
        mask_sum = inputs['attention_mask'].sum(dim=-1)

        is_single_sequence = not mask_sum.shape

        if is_single_sequence:
            # mask sum is a scalar.
            span_idx = [[prompt_len, mask_sum]]
        else:
            span_idx = [[prompt_len, total_len] for total_len in mask_sum]

        sample_attn_scores = []

        for sample_idx in range(len(span_idx)):
            # layers_attn_scores = []
            # attn_ -> layers x samples x heads x seq. len x seq. len
            start, end = span_idx[sample_idx]
            # sample_KER -> layers x heads x span x span
            sample_KER = attn_[:, sample_idx, :, start: end, start: end]
            # log det mean over tokens (after taking diagonal, it's the last dim) and then sum over heads (2nd dim from the left side).
            layers_attn_scores = torch.diagonal(sample_KER, dim1=-2, dim2=-1).log().mean(dim=-1).sum(dim=1)
            sample_attn_scores.append(layers_attn_scores)

        samples_attn_scores.append(sample_attn_scores)

        torch.cuda.empty_cache()

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()

    return np.array(samples_attn_scores)

In [11]:
def get_uncertainity_scores(preference_pairs: dict[str: dict[str: str]], first_k: int = 100) -> np.ndarray:
    """
    TODO: Improve the throughput for higher batches of responses. Right now it is just a pair of responses.
    """
    model = LlamaForCausalLM.from_pretrained(ref_model_path, device_map='cuda:0', dtype=torch.bfloat16)
    model.requires_grad_(False)
    
    if model.generation_config.temperature is None:
        model.generation_config.temperature = 1.0

    # already set
    model.generation_config.do_sample = True

    tokenizer = AutoTokenizer.from_pretrained(ref_model_path)

    model.set_attn_implementation('eager')

    samples_attn_scores = []

    if first_k <= 0:
        first_k = len(preference_pairs)

    pbar_prefernces = tqdm(list(preference_pairs.items())[:first_k])

    for idx, (prompt, pairs) in enumerate(pbar_prefernces, start=1):
        pbar_prefernces.set_description(f'Prompt {idx} uncertainty')
        best_response, worst_response = pairs['best_response'], pairs['worst_response']

        inputs = tokenizer([best_response, worst_response], return_tensors='pt', truncation=True, max_length=2048, padding=True)

        kwargs = {
            "input_ids": inputs['input_ids'].to(model.device),
            "attention_mask": inputs['attention_mask'].to(model.device),
            "use_cache": False,
            "past_key_values": None,
            "output_attentions": True,
            "output_hidden_states": False,
            "return_dict": True,
        }

        with torch.no_grad():
            output = model(**kwargs)

        attns = output.attentions

        # No squeezing
        attn_ = [x.to(torch.float32).detach().cpu() for x in attns]

        prompt_len = len(tokenizer(prompt)['input_ids'])
        mask_sum = inputs['attention_mask'].sum(dim=-1)

        is_single_sequence = not mask_sum.shape

        if is_single_sequence:
            # mask sum is a scalar.
            span_idx = [[prompt_len, mask_sum]]
        else:
            span_idx = [[prompt_len, total_len] for total_len in mask_sum]

        sample_attn_scores = []

        for sample_idx in range(len(span_idx)):
            layers_attn_scores = []
            for block_idx in range(len(attns)):
                eigen_score = 0.0
                for head_idx in range(1, len(attn_[block_idx][sample_idx])):
                    # attn_ is a tuple of attention matrices. With size Batch x head x Sequence len x Sequence len
                    _KER = attn_[block_idx][sample_idx][head_idx]
                    start, end = span_idx[sample_idx]
                    KER = _KER[start: end, start: end]

                    eigen_score += KER.diagonal().log().mean()
                layers_attn_scores.append(eigen_score.item())

            sample_attn_scores.append(layers_attn_scores)

        samples_attn_scores.append(sample_attn_scores)

        torch.cuda.empty_cache()

    del model, tokenizer
    gc.collect()
    torch.cuda.empty_cache()

    return np.array(samples_attn_scores)

In [ ]:
uncertainty_scores_path = os.path.join(os.getcwd(), 'scores_10k.npz')
if not os.path.exists(uncertainty_scores_path):
    scores_10000 = get_uncertainity_scores(preference_pairs, first_k=10000)
    scores_2000 = scores_10000[:2000]
    scores_200 = scores_10000[:200]

    np.savez_compressed(os.path.join(os.getcwd(), 'scores_10k.npz'), scores_10000)
    np.savez_compressed(os.path.join(os.getcwd(), 'scores_2k.npz'), scores_2000)
    np.savez_compressed(os.path.join(os.getcwd(), 'scores_200.npz'), scores_200)
else:
    scores_10000 = np.load(os.path.join(os.getcwd(), 'scores_10k.npz'))['arr_0']
    scores_2000 = np.load(os.path.join(os.getcwd(), 'scores_2k.npz'))['arr_0']
    scores_200 = np.load(os.path.join(os.getcwd(), 'scores_200.npz'))['arr_0']

In [24]:
scores_2000 = get_uncertainity_scores(preference_pairs, first_k=2000)

Prompt 2000 uncertainty: 100%|██████████| 2000/2000 [59:00<00:00,  1.77s/it]  


In [29]:
scores_10000 = get_uncertainity_scores(preference_pairs, first_k=10000)

Prompt 10000 uncertainty: 100%|██████████| 10000/10000 [5:11:09<00:00,  1.87s/it] 


In [ ]:
rm_tokenizer = AutoTokenizer.from_pretrained(reward_model_path)

rm_pipe = pipeline(
    "sentiment-analysis",
    model=config.rm_path,
    device=f'cuda:{config.rm_device}',
    tokenizer=rm_tokenizer,
    model_kwargs={"dtype": torch.bfloat16},
    truncation=True,
)

In [13]:
def print_metrics_on_uncertainity_scores(scores: np.ndarray, threshold: float = 1.0):
    # ratio of log eigen values 
    sample_attention_block_uncertainity_mask = (scores[:, 1, :] / scores[:, 0, :]) < threshold

    sample_attention_block_uncertainity_count = sample_attention_block_uncertainity_mask.sum()
    sample_attention_block_certainity_count = (~sample_attention_block_uncertainity_mask).sum()

    sample_mean_uncertainity_mask = (scores[:, 1, :] / scores[:, 0, :]).mean(axis=-1) < threshold

    sample_mean_uncertainity_count = sample_mean_uncertainity_mask.sum()
    sample_mean_certainity_count = (~sample_mean_uncertainity_mask).sum()

    print(f'For threshold value {threshold} {len(scores)} samples had')

    print(f'Attention block counts where uncertainity is present   : {sample_attention_block_uncertainity_count}')
    print(f'Attention block counts where certainity is present     : {sample_attention_block_certainity_count}')

    print(f'Samples detected where uncertainity is present         : {sample_mean_uncertainity_count}')
    print(f'Samples detected where certainity is present           : {sample_mean_certainity_count}')

In [30]:
for threshold in [1.5, 1.4, 1.3, 1.2, 1.1, 1.05, 1.005, 1.00005 ,1.0]:
    print_metrics_on_uncertainity_scores(scores_10000, threshold=threshold)
    print('*' * 80)

For threshold value 1.5 10000 samples had
Attention block counts where uncertainity is present   : 319815
Attention block counts where certainity is present     : 185
Samples detected where uncertainity is present         : 9996
Samples detected where certainity is present           : 4
********************************************************************************
For threshold value 1.4 10000 samples had
Attention block counts where uncertainity is present   : 319680
Attention block counts where certainity is present     : 320
Samples detected where uncertainity is present         : 9995
Samples detected where certainity is present           : 5
********************************************************************************
For threshold value 1.3 10000 samples had
Attention block counts where uncertainity is present   : 319324
Attention block counts where certainity is present     : 676
Samples detected where uncertainity is present         : 9988
Samples detected where certainity

In [15]:
print_metrics_on_uncertainity_scores(scores_10000)

For threshold value 1.0 10000 samples had
Attention block counts where uncertainity is present   : 205874
Attention block counts where certainity is present     : 114126
Samples detected where uncertainity is present         : 6814
Samples detected where certainity is present           : 3186


In [16]:
for threshold in [1.5, 1.4, 1.3, 1.2, 1.1, 1.005, 1.00005 ,1.0]:
    print_metrics_on_uncertainity_scores(scores_2000, threshold=threshold)
    print('*' * 80)

For threshold value 1.5 2000 samples had
Attention block counts where uncertainity is present   : 63988
Attention block counts where certainity is present     : 12
Samples detected where uncertainity is present         : 2000
Samples detected where certainity is present           : 0
********************************************************************************
For threshold value 1.4 2000 samples had
Attention block counts where uncertainity is present   : 63961
Attention block counts where certainity is present     : 39
Samples detected where uncertainity is present         : 1999
Samples detected where certainity is present           : 1
********************************************************************************
For threshold value 1.3 2000 samples had
Attention block counts where uncertainity is present   : 63894
Attention block counts where certainity is present     : 106
Samples detected where uncertainity is present         : 1999
Samples detected where certainity is pres

In [29]:
scores_200.shape

(200, 2, 32)

In [27]:
scores_200[0][0]

array([-150.84275818, -138.31906128, -196.58979797, -156.59933472,
       -145.96615601, -150.52931213, -129.75682068, -131.40637207,
       -125.60826111, -134.65904236, -132.68510437, -136.05809021,
       -104.24207306, -132.39122009, -118.20938873, -125.3552475 ,
       -125.41088104, -129.94017029, -153.50650024, -151.42243958,
       -148.80877686, -140.93400574, -146.02807617, -152.01097107,
       -161.16046143, -160.43185425, -146.24899292, -153.10655212,
       -115.73773956, -150.01724243, -121.30107117,  -93.4316864 ])

In [28]:
scores_200[0][1]

array([-150.26776123, -134.5160675 , -154.78442383, -146.59112549,
       -130.68878174, -134.30236816, -109.23898315, -116.79162598,
        -93.26016235, -102.11379242, -102.10191345, -106.66228485,
        -77.10712433,  -95.91215515,  -80.74992371,  -99.81895447,
       -102.32080841, -115.67222595, -130.74130249, -127.99694061,
       -129.70353699, -125.09207916, -133.72634888, -147.05903625,
       -130.23358154, -132.94363403, -121.65923309, -130.96412659,
        -94.67223358, -119.02914429,  -95.164711  ,  -70.59238434])

In [12]:
scores_200 = get_uncertainity_scores(preference_pairs, first_k=200)

Prompt 200 uncertainty: 100%|██████████| 200/200 [05:38<00:00,  1.69s/it]


In [17]:
for threshold in [1.5, 1.4, 1.3, 1.2, 1.1, 1.005, 1.00005 ,1.0]:
    print_metrics_on_uncertainity_scores(scores_200, threshold=threshold)
    print('*' * 80)

For threshold value 1.5 200 samples had
Attention block counts where uncertainity is present   : 6390
Attention block counts where certainity is present     : 10
Samples detected where uncertainity is present         : 200
Samples detected where certainity is present           : 0
********************************************************************************
For threshold value 1.4 200 samples had
Attention block counts where uncertainity is present   : 6373
Attention block counts where certainity is present     : 27
Samples detected where uncertainity is present         : 199
Samples detected where certainity is present           : 1
********************************************************************************
For threshold value 1.3 200 samples had
Attention block counts where uncertainity is present   : 6360
Attention block counts where certainity is present     : 40
Samples detected where uncertainity is present         : 199
Samples detected where certainity is present       

In [48]:
np.savez_compressed(os.path.join(os.getcwd(), 'scores_10k.npz'), scores_10000)
np.savez_compressed(os.path.join(os.getcwd(), 'scores_2k.npz'), scores_2000)
np.savez_compressed(os.path.join(os.getcwd(), 'scores_200.npz'), scores_200)

In [54]:
(scores_10000[:200] == scores_200).all()

np.True_

Could not test the <it>efficiency</it> properly, many people were running their code on the same GPU.

In [13]:
scores_200_efficient = get_uncertainity_scores_efficient_v2(preference_pairs, first_k=200)

Prompt 200 uncertainty: 100%|██████████| 200/200 [07:10<00:00,  2.15s/it]


In [14]:
(scores_200_efficient == scores_200).all()

np.False_

In [24]:
scores_200_efficient = get_uncertainity_scores_efficient(preference_pairs, first_k=200)

Prompt 200 uncertainty: 100%|██████████| 200/200 [07:07<00:00,  2.14s/it]


In [20]:
scores_200_efficient.shape

(200, 2, 32)

In [25]:
(scores_200_efficient == scores_200).all()

np.False_

In [ ]:
mask = (scores_200[:, 1, :] / scores_200[:, 0, :]) < 1

In [15]:
mask.sum()

np.int64(4092)

In [18]:
(~mask).sum()

np.int64(2308)

In [ ]:
mean_mask = (scores_200[:, 1, :] / scores_200[:, 0, :]).mean(axis=-1) < 1
print(mean_mask.sum())
print((~mean_mask).sum())

142
58


Uncertaintity check

In [89]:
def get_attn_eig_prod(attns, layer_num=15, tok_lens=[], use_toklens=True):
    """Compute an eigenvalue-based attention score by analyzing attention matrices.

    This function takes the attention matrices of a given layer and for each sample,
    computes the mean log of the diagonal elements (assumed to be eigenvalues) across
    all attention heads. Slices are applied if `tok_lens` is used.

    Args:
        attns (list): A list of tuples, each containing attention matrices for all layers
            and heads for a single sample.
        layer_num (int, optional): The layer index to evaluate. Defaults to 15.
        tok_lens (list, optional): A list of (start, end) indices for each sample to slice
            the attention matrices. Defaults to [].
        use_toklens (bool, optional): Whether to slice the attention matrices using `tok_lens`.
            Defaults to True.

    Returns:
        np.array: An array of computed attention-based eigenvalue scores for each sample.
    """
    attn_scores = []

    for i in range(len(attns)):  # iterating over number of samples
        eigscore = 0.0
        for attn_head_num in range(len(attns[i][layer_num])):  # iterating over number of attn heads
            # attns[i][layer_num][j] is of size seq_len x seq_len
            Sigma = attns[i][layer_num][attn_head_num]

            print(Sigma.shape)

            if use_toklens and tok_lens[i]:
                i1, i2 = tok_lens[i][0], tok_lens[i][1]
                Sigma = Sigma[i1:i2, i1:i2]

            eigscore += torch.log(torch.diagonal(Sigma, 0)).mean()
        attn_scores.append(eigscore.item())

    return np.stack(attn_scores)

In [11]:
model = LlamaForCausalLM.from_pretrained(ref_model_path, device_map='cuda', dtype=torch.bfloat16)
tokenizer = AutoTokenizer.from_pretrained(ref_model_path)

Loading checkpoint shards: 100%|██████████| 4/4 [00:03<00:00,  1.05it/s]


In [12]:
print(best_response)

<|start_header_id|>user<|end_header_id|>
Can we conclude from "A man wearing a grass skirt." that "Is standing in the grass among a group of pigs on their backs near the coast."?
Options:
- yes
- no
- it is not possible to tell A step-by-step solution is:
<|eot_id|>
<|start_header_id|>assistant<|end_header_id|>
1. The statement "A man wearing a grass skirt" tells us that there is a man wearing a grass skirt.
2. However, it does not provide any information about the man's location or the surroundings.
3. The statement "Is standing in the grass among a group of pigs on their backs near the coast" describes a specific location and situation.
4. There is no information in the first statement that connects the man wearing a grass skirt to the location or situation described in the second statement.
5. Therefore, we cannot conclude that "Is standing in the grass among a group of pigs on their backs near the coast" based on the information provided in the first statement.

The answer is: no<|

In [53]:
inputs = tokenizer([best_response, worst_response], return_tensors='pt', truncation=True, max_length=2048, padding=True)
# inputs = tokenizer([best_response], return_tensors='pt', truncation=True, max_length=2048, padding=True)
inputs

{'input_ids': tensor([[128000, 128006,    882, 128007,    198,   6854,    584,  32194,    505,
            330,     32,    893,  12512,    264,  16763,  38380,   1210,    430,
            330,   3957,  11509,    304,    279,  16763,   4315,    264,   1912,
            315,  49910,    389,    872,  28678,   3221,    279,  13962,   1210,
           5380,   3883,    512,     12,  10035,    198,     12,    912,    198,
             12,    433,    374,    539,   3284,    311,   3371,    362,   3094,
          14656,  30308,   6425,    374,    512, 128009,    198, 128006,  78191,
         128007,    198,     16,     13,    578,   5224,    330,     32,    893,
          12512,    264,  16763,  38380,      1,  10975,    603,    430,   1070,
            374,    264,    893,  12512,    264,  16763,  38380,    627,     17,
             13,   4452,     11,    433,   1587,    539,   3493,    904,   2038,
            922,    279,    893,    596,   3813,    477,    279,  40190,    627,
             1

In [26]:
len(tokenizer(prompt)['input_ids'])

65

In [54]:
kwargs = {
    "input_ids": inputs['input_ids'].to(model.device),
    "attention_mask": inputs['attention_mask'].to(model.device),
    "use_cache": False,
    "past_key_values": None,
    "output_attentions": True,
    "output_hidden_states": False,
    "return_dict": True,
}

model.set_attn_implementation('eager')

with torch.no_grad():
    output = model(**kwargs)

attns = output.attentions

In [ ]:
# No squeezing
attn_ = [x.to(torch.float32).detach().cpu() for x in attns]

prompt_len = len(tokenizer(prompt)['input_ids'])
mask_sum = inputs['attention_mask'].sum(dim=-1)

is_single_sequence = not mask_sum.shape

if is_single_sequence:
    # mask sum is a scalar.
    span_idx = [[prompt_len, mask_sum]]
else:
    span_idx = [[prompt_len, total_len] for total_len in mask_sum]

sample_attn_scores = []
attn_scores = []
for head_idx in range(1, len(attn_)):
    attn_scores.append(get_attn_eig_prod([attn_], layer_num=head_idx, tok_lens=span_idx))

attn_scores

torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size([208, 208])
torch.Size(

[array([-142.86560059]),
 array([-202.32208252]),
 array([-162.06225586]),
 array([-151.41825867]),
 array([-156.10256958]),
 array([-133.93257141]),
 array([-133.43083191]),
 array([-131.08973694]),
 array([-137.83486938]),
 array([-133.9058075]),
 array([-140.9239502]),
 array([-107.86325073]),
 array([-136.85749817]),
 array([-122.06723785]),
 array([-127.99515533]),
 array([-130.8465271]),
 array([-135.32292175]),
 array([-157.84783936]),
 array([-156.59591675]),
 array([-151.01907349]),
 array([-144.39160156]),
 array([-151.51086426]),
 array([-156.84384155]),
 array([-166.85919189]),
 array([-166.90963745]),
 array([-148.17816162]),
 array([-158.60186768]),
 array([-118.64774323]),
 array([-154.79603577]),
 array([-123.10443115]),
 array([-94.35379028])]

In [83]:
attns[0].shape

torch.Size([2, 32, 208, 208])

In [ ]:
# No squeezing
attn_ = [x.to(torch.float32).detach().cpu() for x in attns]

prompt_len = len(tokenizer(prompt)['input_ids'])
mask_sum = inputs['attention_mask'].sum(dim=-1)

is_single_sequence = not mask_sum.shape

if is_single_sequence:
    # mask sum is a scalar.
    span_idx = [[prompt_len, mask_sum]]
else:
    span_idx = [[prompt_len, total_len] for total_len in mask_sum]

sample_attn_scores = []

for sample_idx in range(len(span_idx)):
    layers_attn_scores = []
    for block_idx in range(len(attns)):
        eigen_score = 0.0
        for head_idx in range(1, len(attn_[block_idx][sample_idx])):
            # attn_ is a tuple of attention matrices. With size Batch x Layer x Sequence len x Sequence len
            _KER = attn_[block_idx][sample_idx][head_idx]
            start, end = span_idx[sample_idx]
            KER = _KER[start: end, start: end]

            eigen_score += KER.diagonal().log().mean()
        layers_attn_scores.append(eigen_score.item())

    sample_attn_scores.append(layers_attn_scores)

sample_attn_scores = np.array(sample_attn_scores)
sample_attn_scores

array([[-150.84275818, -138.31906128, -196.58979797, -156.59933472,
        -145.96615601, -150.52931213, -129.75682068, -131.40637207,
        -125.60826111, -134.65904236, -132.68510437, -136.05809021,
        -104.24207306, -132.39122009, -118.20938873, -125.3552475 ,
        -125.41088104, -129.94017029, -153.50650024, -151.42243958,
        -148.80877686, -140.93400574, -146.02807617, -152.01097107,
        -161.16046143, -160.43185425, -146.24899292, -153.10655212,
        -115.73773956, -150.01724243, -121.30107117,  -93.4316864 ],
       [-150.26776123, -134.5160675 , -154.78442383, -146.59112549,
        -130.68878174, -134.30236816, -109.23898315, -116.79162598,
         -93.26016235, -102.11379242, -102.10191345, -106.66228485,
         -77.10712433,  -95.91215515,  -80.74992371,  -99.81895447,
        -102.32080841, -115.67222595, -130.74130249, -127.99694061,
        -129.70353699, -125.09207916, -133.72634888, -147.05903625,
        -130.23358154, -132.94363403, -121.6592

Ratio of log det eigen values is lower for 'bad' to 'good' responses?

In [97]:
sample_attn_scores[1] / sample_attn_scores[0]

array([0.9961881 , 0.97250564, 0.78734718, 0.93609035, 0.89533619,
       0.89220077, 0.84187469, 0.88878206, 0.74246838, 0.75831367,
       0.76950547, 0.78394666, 0.73969293, 0.72446009, 0.68310922,
       0.7962886 , 0.81588462, 0.89019605, 0.8516988 , 0.84529704,
       0.87161214, 0.8875933 , 0.91575779, 0.96742383, 0.80809884,
       0.82866108, 0.83186373, 0.85537898, 0.81798931, 0.79343642,
       0.78453315, 0.75555079])

In [99]:
((sample_attn_scores[1] / sample_attn_scores[0]) < 1).all()

np.True_